filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /host-log/*.log
    - /host-log/syslog
    - /host-log/messages

output.elasticsearch:
  enabled: true
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

